### ISSUE TITLE
Cannot read properties of undefined (reading 'method')

### ISSUE THREAD

**Issue by matbeedotcom** [TimHolden/figma-mcp-server#1]
```
> figma-mcp-server@1.0.0 start
> node dist/index.js

TypeError: Cannot read properties of undefined (reading 'method')
    at Server.setRequestHandler (file:///home/acidhax/Documents/Cline/MCP/figma-mcp-server/node_modules/@modelcontextprotocol/sdk/dist/shared/protocol.js:272:44)
    at FigmaAPIServer.setupAPIHandlers (file:///home/acidhax/Documents/Cline/MCP/figma-mcp-server/dist/index.js:43:21)
    at new FigmaAPIServer (file:///home/acidhax/Documents/Cline/MCP/figma-mcp-server/dist/index.js:20:14)
    at main (file:///home/acidhax/Documents/Cline/MCP/figma-mcp-server/dist/index.js:167:20)
```

**Comment by matbeedotcom** [comment]
https://github.com/TimHolden/figma-mcp-server/pull/2
